### ISSUE TITLE
Respect current shell

### ISSUE THREAD

**Issue by andor44** [rimusz/helm-tiller#12]
It'd be nice if this plugin respected the currently running shell instead of [launching `bash` unconditionally](https://github.com/rimusz/helm-tiller/blob/cc8dfc9b8db0a12190f177f4ef558f13047d2f83/scripts/tiller.sh#L122). I use `zsh` personally, and that's what all my autocompletion, etc. are configured for. You could simply check if `$SHELL` is set, and if so use that, otherwise fall back to `bash`. This would also solve problems like #6 without needing to install bash into Alpine based images, for example.

**Comment by rimusz** [comment]
here we go #13
