### ISSUE TITLE
Storage should be configurable

### ISSUE THREAD

**Issue by nikolajbrinch** [rimusz/helm-tiller#25]
Thank you for a wonderful plugin, that really solves a very hard problem.

One small suggestion for an option:

Right now storage is set to secret which makes sense for some deployments, but not all. The developers we give access to our k8s cluster, cannot read/create secrets, so their deployments needs to be able to use configmaps.
We deploy secrets at the admin level, and they are using storage secrets, so it would be very cool to have this options configurable.

**Comment by rimusz** [comment]
sure

**Comment by rimusz** [comment]
here we go, v0.6.3 got that option

**Comment by rimusz** [comment]
To change Tiller storage to `configmap` by setting `HELM_TILLER_STORAGE=configmap`, default is `secret`.
