### ISSUE TITLE
Sharing client host

### ISSUE THREAD

**Issue by sadovnikov** [rimusz/helm-tiller#33]
Seems `helm tiller start` checks presence of already running `tiller` on the client host. If it finds it, the command sets `HELM_HOST` to let `helm` of the user to use the running `tiller`. However the running `tiller` uses `~/.kube/config` and `TILLER_*` environment variables of the user, who started it. By doing this it gives users access even to different K8s clusters.

Expected behavior:
* `helm tiller start` dynamically selects available port and always starts new `tiller`, `HELM_HOST` is set accordingly
* `tiller` does not accept requests from "unknown" shells (maybe by comparing signatures of `~/.kube/config` files)
* `tiller` exits on exit from sub-shell

**Comment by rimusz** [comment]
- helm tiller start dynamically selects available port and always starts new `tiller`, `HELM_HOST` is set accordingly -- this one is not possible to make working as you cannot run multiple tillers on the same host https://github.com/helm/helm/issues/3159

- `tiller` does not accept requests from "unknown" shells (maybe by comparing signatures of `~/.kube/config` files) - be free to open PR for this one :)

- `tiller` exists on exit from sub-shell -- there is `helm tiller stop` be free to open PR for this one :)

**Comment by sadovnikov** [comment]
> helm tiller start dynamically selects available port and always starts new tiller, HELM_HOST is set accordingly -- this one is not possible to make working as you cannot run multiple tillers on the same host

Right, I understand... Although the current behavior somewhat diminishes the purpose of `Tillerless Helm` on shared boxes - `~/.kube/config` of the one who started the tiller is used by others.

> tiller does not accept requests from "unknown" shells (maybe by comparing signatures of ~/.kube/config files) - be free to open PR for this one :)

I'll see if it's doable for me ;)

> tiller exists on exit from sub-shell -- there is helm tiller stop be free to open PR for this one :)

Not really needed if the first one is not possible

**Comment by rimusz** [comment]
`helm Tillerless` plugin is a temporal workaround till helm v3 is available (next summer only).
I do run `helm Tillerless`  in containers, so port is not the issue for me.

**Comment by lulzmachine** [comment]
Regarding the first point, it seems to be possible with this: https://github.com/helm/helm/pull/5557

**Comment by rimusz** [comment]
yes, it will be possible with helm v2.14
