### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by jesseeichar** [rimusz/helm-tiller#34]
Are there any plans to make the plugin work on windows?  I'm currently getting: 

     Error: fork/exec <HOME>\.helm\plugins\helm-tiller/scripts/tiller.sh: %1 is not a valid Win32 application.

**Comment by rimusz** [comment]
sorry I'm not using Windows, cannot really test it there.

**Comment by rimusz** [comment]
from my understanding you need to enable `Windows subsystem for linux` support there

**Comment by jesseeichar** [comment]
is that all :)

Thanks I'll see if I can get it to work.

**Comment by rimusz** [comment]
of course you need Windows 10 64bit one

**Comment by jesseeichar** [comment]
I've just tried this.  Sadly, helm calls proc/fork which apparently is a windows executable so it assumes the file being executed is a windows binary.  It jumps out of the linux environment into the windows environment. 

Current work around: install a linux VM

**Comment by maurtvedt** [comment]
A vote for this one.

**Comment by rimusz** [comment]
I don't have windows computer nor time for adding windows support, if somebody else can chip in here, PR is welcome :)
