### ISSUE TITLE
Add option to output tiller logs to stderr

### ISSUE THREAD

**Issue by rdpa** [rimusz/helm-tiller#35]
Right now there are options to output tiller logs to a file. I would like an option to output tiller logs to stderr after the build for CI log purposes.

**Comment by luisdavim** [comment]
https://github.com/rimusz/helm-tiller/pull/66 should make it easy to implement sending the output to stderr.

**Comment by andrewnazarov** [comment]
#66 has introduced some issues: #67

**Comment by luisdavim** [comment]
I think that if you just set `HELM_TILLER_LOGS_DIR` to `/dev/fd/2` you'll get the tiller logs in `stderr`.

**Comment by luisdavim** [comment]
I've opened https://github.com/rimusz/helm-tiller/pull/69 to address the issues caused by https://github.com/rimusz/helm-tiller/pull/66 sorry about that.
