### ISSUE TITLE
helm_env

### ISSUE THREAD

**Issue by dakky** [rimusz/helm-tiller#37]
#36 breaks the setting of environment variables

See here:

https://github.com/rimusz/helm-tiller/commit/b1d730feb26670c24ef93414d40611cde2af4e11#diff-b2607c8a48fb3dc88826a1def0c39765L167

The removal of `eval '$(helm_env "$@")'` removes the actual setting of the environment variables.
In fact helm_env now simply echoes two lines of tiller host and namespace but does NOT set them 
=> tiller tries to use the default namespace

**Comment by rimusz** [comment]
right, thanks for pointing it out, I did not notice this issue as I'm using default `kube-system` namespace to store releases. I think I'm going to revert it back

**Comment by dakky** [comment]
This PR *should* fix the problem. I quick testrun looked fine.
