### ISSUE TITLE
[ Issue ] Installing the config in anything other than kube-system doesn't save release

### ISSUE THREAD

**Issue by Typositoire** [rimusz/helm-tiller#39]
Using the plugin if I run `helm tiller run XYZ -- helm list` after installing a chart, if XYZ != kube-system I can't find my releases.

**Comment by Typositoire** [comment]
I'm using configmap as storage

**Comment by Typositoire** [comment]
After more debugging it seems to be `escaping` related. I can install some chart outside of kube-system (for config storage) but others fail with weird issues.

**Comment by Typositoire** [comment]
Concrete occurrence of this 
```
Release "netbox" does not exist. Installing it now.
NAME:   netbox
Error: getting deployed release "netbox": release: "netbox" not found
Stopping Tiller...
Error: plugin "tiller" exited with error
```

Helm finish installing Netbox but can't fetch the release after.

```
Installed Helm version v2.10.0
Installed Tiller version v2.10.0
Helm and Tiller are the same version!
Starting Tiller...
Tiller namespace: sre-netbox
Running: helm list

Stopping Tiller...
```
But it installed correctly, just unable to update or purge...
![image](https://user-images.githubusercontent.com/721017/55888593-9f1c9180-5b7d-11e9-8696-b8682fb96ac5.png)

**Comment by Typositoire** [comment]
I doubt it's a bug of this plugin but it's a nice to know.. If the namespace doesn't exist FIRST helm doesn't dumb the release config but still installs everything. I guess they never though a namespace where config reside would not exist upon running install.

**Comment by rimusz** [comment]
Hi, can you provide the exact step you doing and what you are trying to achieve.
Otherwise I cannot link your messages together yet.

**Comment by Typositoire** [comment]
Sorry when im debug mode Im not always clear

When deploying using a tiller-namespace that does not yet exist, the release.vX doesnt get created.

I guess this is because im a normal helm/tiller environment the tiller environment always exist since tiller is installed in it. You can either close this issue or if you're willing I can make a pull request to check that the tiller namespace exist, otherwise create it.

**Comment by rimusz** [comment]
yes, setting tiller namespace and running tiller it will not create the namespace if it is missing.
PR is welcome :)

**Comment by Typositoire** [comment]
Well the issue is coming from the fact that helm creates the namespace but too late for it to use it for it's config storage xD

**Comment by rimusz** [comment]
if you want to use the same namespace for tiller releases as helm releases, the namespace needs to be precreated in advance

**Comment by Typositoire** [comment]
Is it documented somewhere and I just missed it ?

**Comment by rimusz** [comment]
Not sure that's well documented, but I will update the plugin readme.

**Comment by rimusz** [comment]
#40 is merged and released, thanks for the PR 👍
