### ISSUE TITLE
[Question] Do I still need the tiller service account?

### ISSUE THREAD

**Issue by isen-ng** [rimusz/helm-tiller#43]
Sorry, I'm like super new to kubernetes in general but I'm kinda sick of always getting helm and tiller version mismatches.

So, do I still need the tiller service account If i'm using this tiller plugin instead of the remote tiller? 

And.. I assume this plugin will get rid of helm and tiller version mismatches issues right?

**Comment by rimusz** [comment]
As it mentions here https://github.com/rimusz/helm-tiller#installation you don't need to install tiller to the cluster nor tiller service account -  as such setup is not very secure :)

And of course this plugin sorts out helm and tiller version mismatches issues

**Comment by isen-ng** [comment]
Nice! Thank you!

**Comment by isen-ng** [comment]
If anyone is looking, i managed to use this with the terraform helm provider by setting the helm provider host.

```
provider "helm"
  host = "127.0.0.1:44134"
  install_tiller = false
}
```

**Comment by rimusz** [comment]
@isen-ng would you mind to do a PR to update readme with terraform helm provider example?

**Comment by isen-ng** [comment]
Of course I won't mind.

I'll send it tonight or tomorrow.

I'm also testing against minikube, and when I delete and start minikube,
helm tiller needs to stop and start again.

I'll also try to include this tidbit of information.

**Comment by rimusz** [comment]
thank you

**Comment by isen-ng** [comment]
sent https://github.com/rimusz/helm-tiller/pull/44
