### ISSUE TITLE
Lost state?

### ISSUE THREAD

**Issue by whyvez** [rimusz/helm-tiller#56]
Does helm-tiller maintain state somewhere? On a tiller stop/start, I lose my releases. I can see my release on my cluster but `helm release` does not return anything. I can also see releases from other namespaces but not in my own. Could it be because I didn't stop tiller using the `stop` command?

Here is an example of the steps to replicate this issue.

- start tiller 👉 `helm tiller start`
- install release 👉 `helm install `
- list releases, release shows 👉 `helm list`
- computer restart
- start tiller
- list releases, no releases

What am I doing wrong?

**Comment by whyvez** [comment]
If I run `kubectl get pods` I see the pods for my release.

**Comment by whyvez** [comment]
I tried duplicating the issue without success. How could this disconnect happen? How could helm/tiller not know of a release it has done in the past?

**Comment by rimusz** [comment]
cannot really comment on the issue, not sure why it not work for you
