### ISSUE TITLE
/tiller.sh: line 188: 69870 Terminated: 15  

### ISSUE THREAD

**Issue by bitsofinfo** [rimusz/helm-tiller#57]
I do a `helm tiller run -- helm delete --purge [release]`, it basically hangs for a while. The release is stuck in a DELETING state... I can't get rid of it because of this

What does this mean?

```
.helm/plugins/helm-tiller/scripts/tiller.sh: line 188: 69870 Terminated: 15          ./bin/tiller --storage=${HELM_TILLER_STORAGE} --listen=127.0.0.1:${HELM_TILLER_PORT} ${PROBE_LISTEN_FLAG} --history-max=${HELM_TILLER_HISTORY_MAX}  (wd: ~/.helm/plugins/helm-tiller)
```

**Comment by rimusz** [comment]
does the `helm tiller run -- helm ls` work for you?
the `terminated` means that `helm delete --purge [release]` was finished and `tiller` was killed

**Comment by vladislavPV** [comment]
I had almost the same issue.
it was showing me a terminate message from tiller sub shell on bash 4.4 but not on bash 5.
To fix it i had to update this line 
https://github.com/rimusz/helm-tiller/blob/master/scripts/tiller.sh#L163

to be like this 
```bash
( ./bin/tiller --storage=${HELM_TILLER_STORAGE} --listen=127.0.0.1:${HELM_TILLER_PORT} ${PROBE_LISTEN_FLAG} --history-max=${HELM_TILLER_HISTORY_MAX} & 2>"${HELM_TILLER_LOGS_DIR}")
```
found here 
https://stackoverflow.com/questions/81520/how-to-suppress-terminated-message-after-killing-in-bash

@rimusz do you want me to make a PR for this?

**Comment by rimusz** [comment]
yes, please

**Comment by vladislavPV** [comment]
https://github.com/rimusz/helm-tiller/pull/58
