### ISSUE TITLE
Tiller isn't able to find pid file

### ISSUE THREAD

**Issue by konstantinwirz** [rimusz/helm-tiller#62]
My build pipeline doesn't work properly anymore after last update (~3h hours ago) of the tiller plugin.
The error message:

> -------------------------------------------------------------
> Stopping Tiller...
> can not find tiller pid file /helm-tiller-44134.pid
> Error: plugin "tiller" exited with error
> -------------------------------------------------------------

Would you please rollback the pid changes?

**Comment by rimusz** [comment]
please latest v0.8.6, if that still fails for you I will roll back the plugin release.

But ideally you shouldn't be using latest release, pin to some version which works for you so you 
don't get surprises with the new releases :-)

**Comment by deploymentking** [comment]
I can confirm that I have no issues with 0.8.4 and I have the same issue as @konstantinwirz in 0.8.5 and 0.8.6.
To pin a version use this command...
```helm plugin install https://github.com/rimusz/helm-tiller --version 0.8.4```

**Comment by rimusz** [comment]
ok, I’m going to revert code back to 0.8.4

**Comment by rimusz** [comment]
#63 reverted code back to v0.8.4
released v0.8.7 https://github.com/rimusz/helm-tiller/releases/tag/v0.8.7
