### ISSUE TITLE
Latest commit is causing failure when running non-interactive: /dev/tty: No such device or address

### ISSUE THREAD

**Issue by JtMotoX** [rimusz/helm-tiller#67]
The commit below is breaking all helm install when running non-interactive.

**Error:**
/home/***/.helm/plugins/helm-tiller/scripts/tiller.sh: line 79: /dev/tty: No such device or address

**Commit:**
[tiller installation should not break the silence](https://github.com/rimusz/helm-tiller/commit/7d4d68311c413f8a4758a4afe316b247926175e3#diff-b2607c8a48fb3dc88826a1def0c39765)

**Commit Snip:**
```
16: REDIRECT=/dev/tty
17: if [[ "${HELM_TILLER_SILENT}" != "false" ]]; then
18:   REDIRECT=/dev/null
19: fi
. . .
79: echo "Installed Helm version $INSTALLED_HELM" &> $REDIRECT
```

**System Info:**
```
-bash-4.2$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.6 (Maipo)
Release:        7.6
Codename:       Maipo

-bash-4.2$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Comment by rimusz** [comment]
ok, I'm going to revert back the last release and keep that way from now, as I see it is very difficult to make work for everybody.

**Comment by luisdavim** [comment]
Oh, I'm sorry about that. I didn't thought about non interactive. I think that my solution would work for both cases if we replace `/dev/tty` with `/dev/fd/1` would you mind trying that?

**Comment by rimusz** [comment]
for now I reverted back code to v0.9.1 in v0.9.3

**Comment by luisdavim** [comment]
but your fix was to revert the changes, we can keep the changes and use `/dev/fd/1` instead of `/dev/tty`

**Comment by luisdavim** [comment]
please give https://github.com/rimusz/helm-tiller/pull/69 a try

**Comment by rimusz** [comment]
yes, for now I reverted changes back to the code which works.
@luisdavim please test #69 on Mac and Linux, also in linux containers, as I do not have time to do such testing myself.

**Comment by luisdavim** [comment]
Sure, I'll run some tests.
