### ISSUE TITLE
Helm Tiller Version Error with Helm installed via Homebrew

### ISSUE THREAD

**Issue by cmoone** [rimusz/helm-tiller#70]
I installed Helm using Homebrew and installed Helm Tiller plugin. Tried to start Helm Tiller and encountered the following error.

Cortlands-MBP:Downloads cmoone$ helm plugin install https://github.com/rimusz/helm-tiller --version v0.8.4
Installed plugin: tiller
Cortlands-MBP:Downloads cmoone$ helm tiller start kube-system
Installed Helm version g7c22ef9
Installing Tiller vg7c22ef9 ...
version g7c22ef9 does not match the semver scheme 'X.Y.Z(-PRERELEASE)(+BUILD)'. See help for more information.
Error: plugin "tiller" exited with error

**Comment by rimusz** [comment]
what `helm version` shows?

**Comment by cmoone** [comment]
Cortlands-MBP:darwin-amd64 cmoone$ helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

Is my version too new?

**Comment by rimusz** [comment]
yup, for v3.0.1 you do not Tillerless plugin, helm 3 is Tillerless already :)
