### ISSUE TITLE
migrating to helm3?

### ISSUE THREAD

**Issue by bitsofinfo** [rimusz/helm-tiller#71]
Can you provide some insights on how to migrate off helm2 w/ this plugin to helm3? I have live workloads I'd like to migrate but its not clear how I can even have both helm2 and helm3 client binaries w/ this plugin functioning.

```
helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

```
helm2 version
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```

```
helm2 --home ~/.helm2 init --client-only
```

```
helm2 --home ~/.helm2 plugin install https://github.com/rimusz/helm-tiller
```

```
$ helm2 --home ~/.helm2 tiller run -- helm2 list --all
Installed Helm version gafe7058
Installed Tiller version v2.16.3
Installing Tiller vgafe7058 ...
version gafe7058 does not match the semver scheme 'X.Y.Z(-PRERELEASE)(+BUILD)'. See help for more information.
Error: plugin "tiller" exited with error
```

**Comment by rimusz** [comment]
I have written the blog post about it https://rimusz.net/how-to-migrate-from-helm-v2-to-helm-v3
the tool migrates release data only, the actual workload does not get touched or gets restarted/recreated.

**Comment by bitsofinfo** [comment]
hah, yep i just found that, was just going to post that for anyone else blind like myself. READ: https://rimusz.net/how-to-migrate-from-helm-v2-to-helm-v3

:)
